apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "drc.fullname" . }}
  labels:
    {{- include "drc.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.suspend }}
  suspend: {{ .Values.suspend }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "drc.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "drc.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: drc
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args: ["-c", "/config/config.yaml"]
            securityContext:
              {{- toYaml .Values.containerSecurityContext | nindent 14 }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.env }}
            env:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumes:
          - name: config
            configMap:
              name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{ else }}{{ include "drc.fullname" . }}-config{{ end }}
          {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
